import { mockStudents, mockAttendance, mockAssignments, mockLoginLogs, mockAlerts } from "./mockData";
import { mockFeePayments } from "./mockFees";

export interface TrustScoreData {
  studentId: string;
  studentName: string;
  score: number;
  status: "Excellent" | "Good" | "Needs Attention";
  breakdown: {
    attendance: number;
    assignments: number;
    security: number;
    fees: number;
  };
  recommendations: string[];
}

export interface SmartAlert {
  id: string;
  type: "attendance" | "fee" | "security" | "academic";
  title: string;
  message: string;
  priority: "low" | "medium" | "high";
  targetId: string;
  targetName: string;
  timestamp: string;
  resolved: boolean;
}

export interface StudentHealth {
  studentId: string;
  studentName: string;
  overall: "Good" | "Warning" | "Critical";
  attendance: number;
  performance: number;
  feeStatus: "clear" | "pending" | "overdue";
  securityRisk: "low" | "medium" | "high";
  trustScore: number;
}

export interface IncidentReport {
  id: string;
  type: "suspicious_login" | "attendance_issue" | "complaint" | "fee_overdue";
  title: string;
  description: string;
  severity: "low" | "medium" | "high";
  timestamp: string;
  userId: string;
  userName: string;
  autoGenerated: boolean;
}

function getAttendanceScore(studentId: string): number {
  const records = mockAttendance.filter(a => a.studentId === studentId);
  if (records.length === 0) return 25;
  const present = records.filter(a => a.status === "present" || a.status === "late").length;
  return Math.round((present / records.length) * 25);
}

function getAssignmentScore(studentId: string): number {
  const openAssignments = mockAssignments.filter(a => a.status === "open" || a.status === "graded");
  if (openAssignments.length === 0) return 25;
  const completionRate = openAssignments.reduce((sum, a) => sum + (a.totalSubmissions / a.totalStudents), 0) / openAssignments.length;
  return Math.round(completionRate * 25);
}

function getSecurityScore(studentId: string): number {
  const userLogs = mockLoginLogs.filter(l => l.userId === studentId || l.userId === "3");
  if (userLogs.length === 0) return 25;
  const highRisk = userLogs.filter(l => l.riskLevel === "high").length;
  const medRisk = userLogs.filter(l => l.riskLevel === "medium").length;
  const penalty = (highRisk * 8) + (medRisk * 3);
  return Math.max(0, 25 - penalty);
}

function getFeeScore(studentId: string): number {
  const fees = mockFeePayments.filter(f => f.studentId === studentId);
  if (fees.length === 0) return 25;
  const paidRatio = fees.reduce((s, f) => s + f.paidAmount, 0) / fees.reduce((s, f) => s + f.amount, 0);
  const hasOverdue = fees.some(f => f.status === "overdue");
  let score = Math.round(paidRatio * 25);
  if (hasOverdue) score = Math.max(0, score - 5);
  return score;
}

function getRecommendations(breakdown: TrustScoreData["breakdown"]): string[] {
  const recs: string[] = [];
  if (breakdown.attendance < 18) recs.push("📋 Improve class attendance to stay above 75% threshold");
  if (breakdown.assignments < 15) recs.push("📝 Complete pending assignments before deadlines");
  if (breakdown.security < 20) recs.push("🔐 Review login activity and secure your account");
  if (breakdown.fees < 20) recs.push("💰 Clear pending fee dues to avoid penalties");
  if (recs.length === 0) recs.push("✅ Great job! Keep maintaining your excellent performance");
  return recs;
}

export function calculateTrustScore(studentId: string): TrustScoreData {
  const student = mockStudents.find(s => s.id === studentId);
  const breakdown = {
    attendance: getAttendanceScore(studentId),
    assignments: getAssignmentScore(studentId),
    security: getSecurityScore(studentId),
    fees: getFeeScore(studentId),
  };
  const score = breakdown.attendance + breakdown.assignments + breakdown.security + breakdown.fees;
  const status: TrustScoreData["status"] = score >= 80 ? "Excellent" : score >= 60 ? "Good" : "Needs Attention";

  return {
    studentId,
    studentName: student?.name || "Unknown",
    score,
    status,
    breakdown,
    recommendations: getRecommendations(breakdown),
  };
}

export function getAllTrustScores(): TrustScoreData[] {
  return mockStudents.map(s => calculateTrustScore(s.id));
}

export function getStudentHealth(studentId: string): StudentHealth {
  const student = mockStudents.find(s => s.id === studentId);
  const trust = calculateTrustScore(studentId);
  const records = mockAttendance.filter(a => a.studentId === studentId);
  const presentCount = records.filter(a => a.status === "present").length;
  const attendanceRate = records.length > 0 ? Math.round((presentCount / records.length) * 100) : 0;
  const fees = mockFeePayments.filter(f => f.studentId === studentId);
  const hasOverdue = fees.some(f => f.status === "overdue");
  const hasPending = fees.some(f => f.status === "pending" || f.status === "partial");
  const feeStatus: StudentHealth["feeStatus"] = hasOverdue ? "overdue" : hasPending ? "pending" : "clear";
  const userLogs = mockLoginLogs.filter(l => l.userId === "3");
  const highRisk = userLogs.some(l => l.riskLevel === "high");
  const securityRisk: StudentHealth["securityRisk"] = highRisk ? "high" : userLogs.some(l => l.riskLevel === "medium") ? "medium" : "low";

  let overall: StudentHealth["overall"] = "Good";
  if (trust.score < 50 || feeStatus === "overdue" || securityRisk === "high" || attendanceRate < 60) overall = "Critical";
  else if (trust.score < 70 || feeStatus === "pending" || attendanceRate < 75) overall = "Warning";

  return {
    studentId,
    studentName: student?.name || "Unknown",
    overall,
    attendance: attendanceRate,
    performance: Math.round((trust.breakdown.assignments / 25) * 100),
    feeStatus,
    securityRisk,
    trustScore: trust.score,
  };
}

export function generateSmartAlerts(): SmartAlert[] {
  const alerts: SmartAlert[] = [];
  let id = 1;

  mockStudents.forEach(s => {
    const records = mockAttendance.filter(a => a.studentId === s.id);
    const presentCount = records.filter(a => a.status === "present").length;
    const rate = records.length > 0 ? (presentCount / records.length) * 100 : 100;
    if (rate < 75) {
      alerts.push({ id: `sa${id++}`, type: "attendance", title: "Low Attendance Warning", message: `${s.name} has ${Math.round(rate)}% attendance (below 75%)`, priority: rate < 60 ? "high" : "medium", targetId: s.id, targetName: s.name, timestamp: new Date().toISOString(), resolved: false });
    }
  });

  mockFeePayments.filter(f => f.status === "overdue").forEach(f => {
    alerts.push({ id: `sa${id++}`, type: "fee", title: "Fee Overdue", message: `${f.studentName} has overdue ${f.feeName} (₹${(f.amount - f.paidAmount).toLocaleString()})`, priority: "high", targetId: f.studentId, targetName: f.studentName, timestamp: new Date().toISOString(), resolved: false });
  });

  mockFeePayments.filter(f => f.status === "pending").forEach(f => {
    alerts.push({ id: `sa${id++}`, type: "fee", title: "Fee Pending", message: `${f.studentName} - ${f.feeName} payment pending`, priority: "medium", targetId: f.studentId, targetName: f.studentName, timestamp: new Date().toISOString(), resolved: false });
  });

  mockLoginLogs.filter(l => l.riskLevel === "high").forEach(l => {
    alerts.push({ id: `sa${id++}`, type: "security", title: "Suspicious Login Detected", message: `High-risk login attempt for ${l.userName} from ${l.ip}`, priority: "high", targetId: l.userId, targetName: l.userName, timestamp: l.timestamp, resolved: false });
  });

  return alerts;
}

export function generateIncidentReports(): IncidentReport[] {
  const reports: IncidentReport[] = [];
  let id = 1;

  mockLoginLogs.filter(l => l.riskLevel === "high").forEach(l => {
    reports.push({ id: `ir${id++}`, type: "suspicious_login", title: `Suspicious Login - ${l.userName}`, description: `High-risk login (score: ${l.riskScore}) from IP ${l.ip} using ${l.device}. ${l.success ? "Login succeeded." : "Login blocked."}`, severity: "high", timestamp: l.timestamp, userId: l.userId, userName: l.userName, autoGenerated: true });
  });

  mockStudents.forEach(s => {
    const records = mockAttendance.filter(a => a.studentId === s.id);
    const presentCount = records.filter(a => a.status === "present").length;
    const rate = records.length > 0 ? (presentCount / records.length) * 100 : 100;
    if (rate < 75) {
      reports.push({ id: `ir${id++}`, type: "attendance_issue", title: `Low Attendance - ${s.name}`, description: `Attendance rate of ${Math.round(rate)}% is below the 75% minimum threshold. Student is at risk of debarment.`, severity: rate < 60 ? "high" : "medium", timestamp: new Date().toISOString(), userId: s.id, userName: s.name, autoGenerated: true });
    }
  });

  mockFeePayments.filter(f => f.status === "overdue").forEach(f => {
    reports.push({ id: `ir${id++}`, type: "fee_overdue", title: `Fee Overdue - ${f.studentName}`, description: `${f.feeName}: ₹${(f.amount - f.paidAmount).toLocaleString()} overdue. Original due date has passed.`, severity: "medium", timestamp: new Date().toISOString(), userId: f.studentId, userName: f.studentName, autoGenerated: true });
  });

  return reports;
}

export const complaintAnalytics = {
  byCategory: [
    { category: "Hostel", count: 12, fill: "hsl(var(--warning))" },
    { category: "Staff", count: 8, fill: "hsl(var(--destructive))" },
    { category: "Academic", count: 15, fill: "hsl(var(--secondary))" },
    { category: "Infrastructure", count: 6, fill: "hsl(var(--accent))" },
  ],
  byStatus: [
    { status: "Pending", count: 14, fill: "hsl(var(--warning))" },
    { status: "In Progress", count: 8, fill: "hsl(var(--secondary))" },
    { status: "Resolved", count: 16, fill: "hsl(var(--success))" },
    { status: "Dismissed", count: 3, fill: "hsl(var(--muted-foreground))" },
  ],
  topIssues: [
    { issue: "Library timing", count: 5 },
    { issue: "Mess food quality", count: 4 },
    { issue: "Water supply", count: 3 },
    { issue: "Lab equipment", count: 3 },
    { issue: "Staff behavior", count: 2 },
  ],
  trend: [
    { month: "Oct", count: 8 },
    { month: "Nov", count: 12 },
    { month: "Dec", count: 6 },
    { month: "Jan", count: 10 },
    { month: "Feb", count: 14 },
    { month: "Mar", count: 9 },
  ],
};
