import { FileWarning, Download, AlertTriangle, Shield, Users, DollarSign } from "lucide-react";
import AppLayout from "@/components/AppLayout";
import { generateIncidentReports, type IncidentReport } from "@/lib/trustScore";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

const typeConfig: Record<string, { icon: typeof Shield; label: string; color: string }> = {
  suspicious_login: { icon: Shield, label: "Suspicious Login", color: "bg-destructive/10 text-destructive" },
  attendance_issue: { icon: Users, label: "Attendance Issue", color: "bg-warning/10 text-warning" },
  complaint: { icon: AlertTriangle, label: "Complaint", color: "bg-secondary/10 text-secondary" },
  fee_overdue: { icon: DollarSign, label: "Fee Overdue", color: "bg-warning/10 text-warning" },
};

export default function IncidentReportsPage() {
  const reports = generateIncidentReports();

  const downloadReport = (report: IncidentReport) => {
    const text = `INCIDENT REPORT\n${"=".repeat(50)}\nID: ${report.id}\nType: ${report.type}\nTitle: ${report.title}\nSeverity: ${report.severity.toUpperCase()}\nUser: ${report.userName}\nDate: ${new Date(report.timestamp).toLocaleString()}\n\nDescription:\n${report.description}\n\nAuto-generated: ${report.autoGenerated ? "Yes" : "No"}\n${"=".repeat(50)}\nGenerated by EduVerse AuthGuard System`;
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `incident_${report.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AppLayout>
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <FileWarning className="h-6 w-6 text-secondary" /> Auto Incident Reports
          </h1>
          <p className="text-sm text-muted-foreground mt-1">Automatically generated reports for security, attendance, and fee incidents.</p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="bg-card border border-border rounded-xl p-4">
            <div className="text-xs text-muted-foreground">Total Reports</div>
            <div className="text-2xl font-bold mt-1">{reports.length}</div>
          </div>
          <div className="bg-card border border-destructive/20 rounded-xl p-4">
            <div className="text-xs text-muted-foreground">High Severity</div>
            <div className="text-2xl font-bold text-destructive mt-1">{reports.filter(r => r.severity === "high").length}</div>
          </div>
          <div className="bg-card border border-border rounded-xl p-4">
            <div className="text-xs text-muted-foreground">Auto-Generated</div>
            <div className="text-2xl font-bold mt-1">{reports.filter(r => r.autoGenerated).length}</div>
          </div>
        </div>

        <div className="space-y-3">
          {reports.map(report => {
            const config = typeConfig[report.type] || typeConfig.complaint;
            const Icon = config.icon;
            return (
              <div key={report.id} className="bg-card border border-border rounded-xl p-5 hover:shadow-card-hover transition-all">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex gap-3 min-w-0">
                    <div className={cn("h-10 w-10 rounded-lg flex items-center justify-center shrink-0", config.color)}>
                      <Icon className="h-5 w-5" />
                    </div>
                    <div className="min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-semibold text-sm">{report.title}</span>
                        <span className={cn("text-[10px] font-bold px-1.5 py-0.5 rounded uppercase",
                          report.severity === "high" ? "bg-destructive/10 text-destructive" : report.severity === "medium" ? "bg-warning/10 text-warning" : "bg-muted text-muted-foreground"
                        )}>{report.severity}</span>
                        {report.autoGenerated && <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded bg-secondary/10 text-secondary">AUTO</span>}
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">{report.description}</p>
                      <div className="text-[11px] text-muted-foreground mt-1.5 font-mono">
                        {report.userName} · {new Date(report.timestamp).toLocaleString()}
                      </div>
                    </div>
                  </div>
                  <Button size="sm" variant="outline" className="h-8 text-xs shrink-0" onClick={() => downloadReport(report)}>
                    <Download className="h-3 w-3 mr-1" /> Download
                  </Button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </AppLayout>
  );
}
